[package]
name = "floki-cli"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[[bin]]
name = "flk"
path = "src/main.rs"

[dependencies]
anyhow.workspace = true
clap.workspace = true
tracing.workspace = true
interprocess.workspace = true
dirs.workspace = true
floki-proto.workspace = true
floki-mcp.workspace = true
serde_json.workspace = true

[lints]
workspace = true
