[package]
name = "floki-bench"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true
rust-version.workspace = true

[[bin]]
name = "floki-bench"
path = "src/main.rs"

[lib]
name = "floki_bench"
path = "src/lib.rs"

[dependencies]
anyhow.workspace = true
clap.workspace = true
floki-core.workspace = true
serde.workspace = true
serde_json.workspace = true

[target.'cfg(windows)'.dependencies]
windows-sys.workspace = true

[lints]
workspace = true
